jobs:
- job: Build_VS2015
  pool:
    vmImage: 'vs2015-win2012r2'
  strategy:
    matrix:
      v140:
        XP: 0
      v140_xp:
        XP: 1
  steps:
    - script: |
        call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
        set
        python build.py
      env:
        XP: $(XP)
    - script: nuget push *.nupkg %NUGET_API_KEY% -Source https://nuget.org/

- job: Build_VS2017
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      v141:
        XP: 0
      v141_xp:
        XP: 1
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '2.x' 
        addToPath: true 
    - script: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\VsDevCmd.bat"
        set
        where /R "%WindowsSdkDir:~0,-1%" dbghelp.dll
        python build.py
      env:
        XP: $(XP)
    - script: nuget push *.nupkg %NUGET_API_KEY% -Source https://nuget.org/
